apiVersion: apps/v1
kind: Deployment
metadata:
  name: spelling-bee
  labels:
    name: spelling-bee
spec:
  replicas: 4
  selector:
    matchLabels:
      name: spelling-bee
  template:
    metadata:
      name: spelling-bee
      labels:
        name: spelling-bee
    spec:
      containers:
        - name: spelling-bee
          image: rennergade/spelling-bee:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: flask-key
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: pass
            - name: ADMIN_AUTH
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: auth