apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  flask-key: gvZRito+5vAECmFC
  pass: J2I1NDY0ZWQzMTVlNzE3N2NhOWYyYzYzODkzYjE1M2ZhYWJiMDJmNDUyY2QxNDVkZmM5NjcwMTAzNGFjMjFmMDAn
  auth: JzI1NGFhMjQ4YWNiNDdkZDY1NGNhM2VhNTNmNDhjMmMyNmQ2NDFkMjNkN2UyZTkzYTFlYzU2MjU4ZGY3Njc0YzQn